In [71]:
import pandas as pd
df = pd.read_csv("playTennis.csv")
df.head()

    Outlook Temperature Humidity    Wind Play Tennis
0     Sunny         Hot     High    Weak          No
1     Sunny         Hot     High  Strong          No
2  Overcast         Hot     High    Weak         Yes
3      Rain        Mild     High    Weak         Yes
4      Rain        Cool   Normal    Weak         Yes

In [61]:
y = df['Play Tennis']
x = df.drop('Play Tennis', axis = 1)
y

0      No
1      No
2     Yes
3     Yes
4     Yes
5      No
6     Yes
7      No
8     Yes
9     Yes
10    Yes
11    Yes
12    Yes
13     No
Name: Play Tennis, dtype: object

In [62]:
x

     Outlook Temperature Humidity    Wind
0      Sunny         Hot     High    Weak
1      Sunny         Hot     High  Strong
2   Overcast         Hot     High    Weak
3       Rain        Mild     High    Weak
4       Rain        Cool   Normal    Weak
5       Rain        Cool   Normal  Strong
6   Overcast        Cool   Normal  Strong
7      Sunny        Mild     High    Weak
8      Sunny        Cool   Normal    Weak
9       Rain        Mild   Normal    Weak
10     Sunny        Mild   Normal  Strong
11  Overcast        Mild     High  Strong
12  Overcast         Hot   Normal    Weak
13      Rain        Mild     High  Strong

In [63]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x.Outlook = le.fit_transform(df['Outlook'])
x.Temperature = le.fit_transform(df['Temperature'])
x.Humidity = le.fit_transform(df['Humidity'])
x.Wind = le.fit_transform(df['Wind'])
x

    Outlook  Temperature  Humidity  Wind
0         2            1         0     1
1         2            1         0     0
2         0            1         0     1
3         1            2         0     1
4         1            0         1     1
5         1            0         1     0
6         0            0         1     0
7         2            2         0     1
8         2            0         1     1
9         1            2         1     1
10        2            2         1     0
11        0            2         0     0
12        0            1         1     1
13        1            2         0     0

In [64]:
import warnings
warnings.filterwarnings('ignore')
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(x,y)
predicted = model.predict([[2,0,0,1]])
print('Predicted Value',predicted)

Predicted Value ['No']

In [65]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)
from sklearn.naive_bayes import GaussianNB
model_gnb = GaussianNB()
model_gnb.fit(x_train,y_train)
y_pred = model_gnb.predict(x_test)

from sklearn.metrics import accuracy_score
print(f'Model accuracy score : {100*accuracy_score(y_test,y_pred):0.2f}%')
print()

Model accuracy score : 66.67%

In [66]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
print("confusion metrix")
print(cm)

confusion metrix
[[1 1]
 [0 1]]

In [67]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

          No       1.00      0.50      0.67         2
         Yes       0.50      1.00      0.67         1

    accuracy                           0.67         3
   macro avg       0.75      0.75      0.67         3
weighted avg       0.83      0.67      0.67         3

In [68]:
x = df.drop('Play Tennis',axis = 1)
from sklearn.preprocessing import OneHotEncoder
le = OneHotEncoder()

y = pd.get_dummies(df,columns=['Outlook','Temperature','Humidity','Wind'])
print(y)

   Play Tennis  Outlook_Overcast  Outlook_Rain  Outlook_Sunny  \
0           No             False         False           True
1           No             False         False           True
2          Yes              True         False          False
3          Yes             False          True          False
4          Yes             False          True          False
5           No             False          True          False
6          Yes              True         False          False
7           No             False         False           True
8          Yes             False         False           True
9          Yes             False          True          False
10         Yes             False         False           True
11         Yes              True         False          False
12         Yes              True         False          False
13          No             False          True          False

    Temperature_Cool  Temperature_Hot  Temperature_Mild  Humidity_High  \
0              False             True             False           True
1              False             True             False           True
2              False             True             False           True
3              False            False              True           True
4               True            False             False          False
5               True            False             False          False
6               True            False             False          False
7              False            False              True           True
8               True            False             False          False
9              False            False              True          False
10             False            False              True          False
11             False            False              True           True
12             False             True             False          False
13             False            False              True           True

    Humidity_Normal  Wind_Strong  Wind_Weak
0             False        False       True
1             False         True      False
2             False        False       True
3             False        False       True
4              True        False       True
5              True         True      False
6              True         True      False
7             False        False       True
8              True        False       True
9              True        False       True
10             True         True      False
11            False         True      False
12             True        False       True
13            False         True      False

In [70]:
x = df.drop('Play Tennis',axis = 1)
from sklearn.preprocessing import OneHotEncoder
le = OneHotEncoder()
enc_data = pd.DataFrame(le.fit_transform(df[['Outlook','Temperature','Humidity','Wind']]).toarray())
New_df = df.join(enc_data)
print(enc_data)
print(New_df)

      0    1    2    3    4    5    6    7    8    9
0   0.0  0.0  1.0  0.0  1.0  0.0  1.0  0.0  0.0  1.0
1   0.0  0.0  1.0  0.0  1.0  0.0  1.0  0.0  1.0  0.0
2   1.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  1.0
3   0.0  1.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0
4   0.0  1.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  1.0
5   0.0  1.0  0.0  1.0  0.0  0.0  0.0  1.0  1.0  0.0
6   1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  1.0  0.0
7   0.0  0.0  1.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0
8   0.0  0.0  1.0  1.0  0.0  0.0  0.0  1.0  0.0  1.0
9   0.0  1.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  1.0
10  0.0  0.0  1.0  0.0  0.0  1.0  0.0  1.0  1.0  0.0
11  1.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  1.0  0.0
12  1.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  1.0
13  0.0  1.0  0.0  0.0  0.0  1.0  1.0  0.0  1.0  0.0
     Outlook Temperature Humidity    Wind Play Tennis    0    1    2    3  \
0      Sunny         Hot     High    Weak          No  0.0  0.0  1.0  0.0
1      Sunny         Hot     High  Strong          No  0.0  0.0  1.0  0.0
2   Overcast         Hot     High    Weak         Yes  1.0  0.0  0.0  0.0
3       Rain        Mild     High    Weak         Yes  0.0  1.0  0.0  0.0
4       Rain        Cool   Normal    Weak         Yes  0.0  1.0  0.0  1.0
5       Rain        Cool   Normal  Strong          No  0.0  1.0  0.0  1.0
6   Overcast        Cool   Normal  Strong         Yes  1.0  0.0  0.0  1.0
7      Sunny        Mild     High    Weak          No  0.0  0.0  1.0  0.0
8      Sunny        Cool   Normal    Weak         Yes  0.0  0.0  1.0  1.0
9       Rain        Mild   Normal    Weak         Yes  0.0  1.0  0.0  0.0
10     Sunny        Mild   Normal  Strong         Yes  0.0  0.0  1.0  0.0
11  Overcast        Mild     High  Strong         Yes  1.0  0.0  0.0  0.0
12  Overcast         Hot   Normal    Weak         Yes  1.0  0.0  0.0  0.0
13      Rain        Mild     High  Strong          No  0.0  1.0  0.0  0.0

      4    5    6    7    8    9
0   1.0  0.0  1.0  0.0  0.0  1.0
1   1.0  0.0  1.0  0.0  1.0  0.0
2   1.0  0.0  1.0  0.0  0.0  1.0
3   0.0  1.0  1.0  0.0  0.0  1.0
4   0.0  0.0  0.0  1.0  0.0  1.0
5   0.0  0.0  0.0  1.0  1.0  0.0
6   0.0  0.0  0.0  1.0  1.0  0.0
7   0.0  1.0  1.0  0.0  0.0  1.0
8   0.0  0.0  0.0  1.0  0.0  1.0
9   0.0  1.0  0.0  1.0  0.0  1.0
10  0.0  1.0  0.0  1.0  1.0  0.0
11  0.0  1.0  1.0  0.0  1.0  0.0
12  1.0  0.0  0.0  1.0  0.0  1.0
13  0.0  1.0  1.0  0.0  1.0  0.0

In [ ]:
import pandas as pd
data = pd.read_csv('PlayTennis.csv')
x = df.drop(['Play Tennis'],axis = 1)
y = df['Play Tennis']
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=42)
from sklearn.preprocessing import OneHotEncoder
cols = ['Outlook','Temperature','Humidity','Wind']
encoder = OneHotEncoder(sparse_output = False)
x_train = encoder.fit_transform(x_train[cols])
x_test = encoder.transform(x_test[cols])

from sklearn.naive_bayes import GaussianNB
model_gnb = GaussianNB()
model_gnb.fit(x_train,y_train)
y_pred = model_gnb.predict(x_test)
from sklearn.metrics import accuracy_score
print(f'model accuracy score : {100 * accuracy_score(y_test,y_pred):0.2f}%')
print()
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
print('confussion Mtarix')
print(cm)

model accuracy score : 80.00%

confussion Mtarix
[[1 1]
 [0 3]]